// Code generated by acp catalog codegen. DO NOT EDIT.
// Source: apps/server/src/acp/catalog/registry.snapshot.json
import { z } from "zod"

export const AgentIdSchema = z.string().min(1)

export type AgentId = z.infer<typeof AgentIdSchema>
