import { CatalogAgentEntry } from "./build.catalog.entries"

const generatedBanner = `// Code generated by acp catalog codegen. DO NOT EDIT.
// Source: apps/server/src/acp/catalog/registry.snapshot.json
`

const quote = (value: string): string => JSON.stringify(value)

const renderStringOrNull = (value: string | null): string =>
  value === null ? "null" : quote(value)

const renderCommand = (command: readonly string[]): string =>
  `[${command.map((part) => quote(part)).join(", ")}]`

const renderSpawn = (entry: CatalogAgentEntry): string => `{
      kind: ${quote(entry.spawn.kind)},
      binaryName: ${quote(entry.spawn.binaryName)},
      command: ${renderCommand(entry.spawn.command)},
    }`

const renderCatalogEntry = (entry: CatalogAgentEntry): string => `  ${quote(entry.id)}: {
    id: ${quote(entry.id)},
    displayName: ${quote(entry.displayName)},
    description: ${renderStringOrNull(entry.description)},
    version: ${renderStringOrNull(entry.version)},
    icon: ${renderStringOrNull(entry.icon)},
    available: true,
    spawn: ${renderSpawn(entry)},
    authMethodId: ${quote(entry.authMethodId)},
  }`

export const renderAgentIdGenerated = (entries: readonly CatalogAgentEntry[]): string => {
  const ids = entries.map((entry) => quote(entry.id)).join(",\n  ")

  return `${generatedBanner}import { z } from "zod"

export const AgentIdSchema = z.enum([
  ${ids},
])

export type AgentId = z.infer<typeof AgentIdSchema>
`
}

export const renderCatalogAgentsGenerated = (
  entries: readonly CatalogAgentEntry[],
): string => `${generatedBanner}export type CatalogSpawnKind = "binary" | "npx" | "uvx"

export type CatalogSpawn = {
  readonly kind: CatalogSpawnKind
  readonly binaryName: string
  readonly command: readonly string[]
}

export type CatalogAgent = {
  readonly id: string
  readonly displayName: string
  readonly description: string | null
  readonly version: string | null
  readonly icon: string | null
  readonly available: true
  readonly spawn: CatalogSpawn
  readonly authMethodId: string
}

export const catalogAgentsById = {
${entries.map(renderCatalogEntry).join(",\n")},
} as const satisfies Record<string, CatalogAgent>

export const catalogAgentList: readonly CatalogAgent[] = Object.values(catalogAgentsById)

export const catalogAgentIds = [
${entries.map((entry) => `  ${quote(entry.id)}`).join(",\n")},
] as const
`

export const renderAgentOverridesGenerated = (
  entries: readonly CatalogAgentEntry[],
): string => {
  const skeletonLines = entries
    .map(
      (entry) => `  ${quote(entry.id)}: {
    // Empty override skeleton. Product overrides live in overrides/*.override.ts.
  }`,
    )
    .join(",\n")

  return `${generatedBanner}export type AgentProfileOverrideSkeleton = {
  readonly command?: readonly string[]
  readonly authMethodId?: string
}

export const generatedAgentOverrideSkeletonsById = {
${skeletonLines},
} as const satisfies Record<string, AgentProfileOverrideSkeleton>
`
}
