import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const webDistDir = path.join(import.meta.dir, "..", "..", "..", "web", "dist")
const generatedDir = path.join(import.meta.dir, "..", "..", ".generated")
const outFile = path.join(generatedDir, "console.assets.generated.ts")

type CollectedAsset = {
  path: string
  base64: string
}

const collect = async (dir: string): Promise<Array<CollectedAsset>> => {
  const dirents = await readdir(dir, { withFileTypes: true, recursive: true })
  const files = dirents
    .filter((dirent) => dirent.isFile())
    .map((dirent) => path.join(dirent.parentPath, dirent.name))
    .sort()

  return Promise.all(
    files.map(async (file) => ({
      path: path.relative(dir, file).split(path.sep).join("/"),
      base64: (await readFile(file)).toString("base64"),
    })),
  )
}

const emit = (assets: ReadonlyArray<CollectedAsset>): string =>
  [
    "// generated by src/console/console.assets.codegen.cli.ts. do not edit.",
    "export const consoleAssetEntries: Array<{ path: string; base64: string }> = [",
    ...assets.map(
      (asset) =>
        `  { path: ${JSON.stringify(asset.path)}, base64: ${JSON.stringify(asset.base64)} },`,
    ),
    "]",
    "",
  ].join("\n")

const main = async () => {
  let files: Array<CollectedAsset>
  try {
    files = await collect(webDistDir)
  } catch {
    console.error(
      `[server] console assets not found at ${webDistDir}. Run \`bun run --filter web build\` first.`,
    )
    process.exit(1)
  }
  if (!files.some((asset) => asset.path === "index.html")) {
    console.error(`[server] ${webDistDir} is missing index.html. Is the web build complete?`)
    process.exit(1)
  }
  await mkdir(generatedDir, { recursive: true })
  await writeFile(outFile, emit(files))
  console.log(`[server] embedded ${files.length} console assets into .generated`)
}

await main()
