import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const migrationsFolder = path.join(import.meta.dir, "..", "drizzle")
const generatedDir = path.join(import.meta.dir, "..", "..", "..", ".generated")
const outFile = path.join(generatedDir, "migrations.generated.ts")

type CollectedFile = {
  name: string
  base64: string
}

const collect = async (dir: string): Promise<Array<CollectedFile>> => {
  const dirents = await readdir(dir, { withFileTypes: true, recursive: true })
  const files = dirents
    .filter((dirent) => dirent.isFile())
    .map((dirent) => path.join(dirent.parentPath, dirent.name))
    .sort()

  return Promise.all(
    files.map(async (file) => ({
      name: path.relative(dir, file).split(path.sep).join("/"),
      base64: (await readFile(file)).toString("base64"),
    })),
  )
}

const emit = (files: ReadonlyArray<CollectedFile>): string =>
  [
    "// generated by src/persistence/migrations/migrations.codegen.cli.ts. do not edit.",
    "export const embeddedMigrationEntries: Array<{ name: string; base64: string }> = [",
    ...files.map(
      (file) => `  { name: ${JSON.stringify(file.name)}, base64: ${JSON.stringify(file.base64)} },`,
    ),
    "]",
    "",
  ].join("\n")

const main = async () => {
  const files = await collect(migrationsFolder)
  if (files.length === 0) {
    console.error(`[server] no migration files found in ${migrationsFolder}`)
    process.exit(1)
  }
  await mkdir(generatedDir, { recursive: true })
  await writeFile(outFile, emit(files))
  console.log(`[server] embedded ${files.length} migration files into .generated`)
}

await main()
